name: e_commerce_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.2.2
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Si tu as un dossier assets/images, dÃ©commente les deux lignes ci-dessous :
  # assets:
  #   - assets/images/